### PR TITLE
Edit README.md

### PR DESCRIPTION
**Pull request by Lupie**
- The code snippets should be American spelling. Can we rewrite the code so that works?
- Do we want the build status to show?

### CODE REVIEW

**Comment by Lupie** [comment]
@Raynos

**Comment by Raynos** [comment]
do you we really have to rename `licence` to `license` :(

**Comment by Raynos** [comment]
everything else lgtm.

**Comment by Lupie** [comment]
:(

How many minutes would it take?

I'm thinking the rename will save time in the long run, since it'll be a
bit more intuitive (for most engineers) and match the documentation. But if
it's a huge project of rewriting, that might not be true.

**Comment by macalinao** [comment]
+1

we are in SF

**Comment by Lupie** [comment]
@Raynos hi! I just saw this is still open 😈 

@macalinao I'm going to close this—not sure who still works on this—but hope someone with write access carries the license torch. 🔥

**Comment by Raynos** [comment]
@Lupie thanks for cleanup. Hello from Seoul.

**Comment by Lupie** [comment]
Seoul! Wonderful, hello!

I need to hit you up about some Node project too. 🤓

**Pull request closed without merging**
